### ISSUE TITLE
Crash with Intel driver when default device is AMD

### ISSUE THREAD

**Issue by Ristovski** [AvtechScientific/ASL#10]
The "known" bug that causes a segfault when used with the Intel driver WITH Intel graphics - seems to happen even while the default device/platform is the dedicated GPU (AMD Radeon HD 8850M) running xf86-video-ati/mesa-cl. Even when the user adds --platform and --device arguments, it still accesses the Intel GPU opencl (checked by doing strace):

access("/opt/intel/opencl-sdk/lib64/clbltfnl9_img_cbk.o", F_OK) = 0
open("/opt/intel/opencl-sdk/lib64/clbltfnl9_img_cbk.o", O_RDONLY) = 3

The cause of the segfault is the same as the one in the "known issue" page.

**Comment by AvtechScientific** [comment]
It crashes at this line:
https://github.com/AvtechScientific/ASL/blob/master/src/acl/aclHardware.cxx#L140
during initial scan of available hardware:
https://github.com/AvtechScientific/ASL/blob/master/src/acl/aclHardware.cxx#L106
before it gets to the  --platform and --device arguments.

I'm not sure whether it is acceptable for you, but try to deinstall the Intel driver and use the AMD driver for CPU. Even if you are not going to stay with this in a long run - the result of this experiment is important for  other users (wil publish it on the Deployment page (once back from vacation at the end of the week)).

**Comment by AvtechScientific** [comment]
Hi @Ristovski,
did you manage to work around the problem by using another driver?

Thanks.

**Comment by AvtechScientific** [comment]
Dear comrade @Ristovski ;)

do you experience this issue with the Intel 14.2 runtime? We got reports that everything works fine with that version.

Thanks.

**Comment by Ristovski** [comment]
Hello @AvtechScientific !

I must deeply apologize for my absence as I have been busy! (_sad embarrased emoticon here_)
I have recently switched to gentoo, and I can report that everything works fine! 

I must say that I am impressed of your dedication towards issue reports! :smiley: 
I do not believe anyone else would actively pursue an issue over a 75 day period including the user being absent and not being able to confirm.

You are truly doing excellent work! Keep it up and all of you have a nice weekend!

--Ristovski

###### PS: 'Comrade' was a nice touch! :3
