### ISSUE TITLE
Does ASL have the function to parallel calculating？

### ISSUE THREAD

**Issue by zhaofan19** [AvtechScientific/ASL#19]
Hello，the Avtech scientists. I'm very interested in LBM and ASL software.I have browsed the feature introuction and the source code of ASL,but I haven't see anything about MPI. Could this software running with  large number of CPU nodes？

**Comment by AvtechScientific** [comment]
Yes, you can use MPI externally to run ASL-based applications on multiple nodes with multiple CPUs/GPUs/FPGAs/etc. ASL allows to specify which device(s) to use for data storage/calculations within a node. There are no MPI parts in the ASL code though.
