### ISSUE TITLE
Build errors: redeclaration of <...> may not have default arguments [-fpermissive]

### ISSUE THREAD

**Issue by amiv1** [AvtechScientific/ASL#2]
Build fails on Arch Linux with a few syntax errors like this:

```
error: redeclaration of ‘template<class T> void asl::combineArrays(T*, T*, T*, unsigned int, T*, unsigned int)’ may not have default arguments [-fpermissive]
```

Full error output: http://pastebin.com/Z4ZsLqgQ

**OS:** Arch Linux x86_64
**ASL version:** 0.1.2

**Comment by lupinix** [comment]
I can confirm this issue on Fedora 22.

**Comment by AvtechScientific** [comment]
We have fixed this without relying on -fpermissive - will release it soon...

**Comment by amiv1** [comment]
Still the same issue persists: http://pastebin.com/Y2d27UPM
CMake version: 3.2.3
Defining the **CMAKE_CXX_FLAGS="-fpermissive"** in [this block](https://github.com/AvtechScientific/ASL/blob/4ca5aee8c7bd7cbbbd82c99f26ab84217e3432f1/CMakeLists.txt#L17) works as a workaround again.
