### ISSUE TITLE
FTBFS: error: expected unqualified-id before 'sizeof'

### ISSUE THREAD

**Issue by ghisvail** [AvtechScientific/ASL#22]
Forwarded from [Debian-Bug #822469](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822469). 

We are using g++ 5.3.1 and Boost 1.58 at the moment.

**Comment by AvtechScientific** [comment]
Did you try the current master branch? It should have been fixed some time ago...

**Comment by ghisvail** [comment]
We (Debian) prefer working with official releases rather than snapshots. Please consider tagging a bugfix release or just point me to the relevant commit which addresses this issue so it can be cheery-picked to the current release. Thanks.

**Comment by AvtechScientific** [comment]
Please, try this commit:

https://github.com/AvtechScientific/ASL/commit/003be03b67a818138e0f7590b32932feb3c323c5

**Comment by ghisvail** [comment]
Cherry-picking this commit fixed the issue. Thanks.

**Comment by AvtechScientific** [comment]
Do you still face the issue with POCL (#16) on Debian?

**Comment by ghisvail** [comment]
I have not tried since. Debian is slowly updating pocl to the latest upstream, so I should give it another go once work on the packaging settles.
