### ISSUE TITLE
manpage for asl-hardware

### ISSUE THREAD

**Issue by ghisvail** [AvtechScientific/ASL#28]
Debian, and other Linux distributions, requires that all executables ship with a corresponding [manpage](https://wiki.debian.org/ManPage). Please consider providing one.

**Comment by AvtechScientific** [comment]
1. May we supply it as an '.org' file - 'doc/Man-Pages/asl-hardware.1.org' that can easily be converted to a man page as follows: `pandoc asl-hardware.1.org -s -t man -o asl-hardware.1` ?
2. Is shipping it enough or should we also convert/archive/install it through CMake?

**Comment by ghisvail** [comment]
> May we supply it as an '.org' file - 'doc/Man-Pages/asl-hardware.1.org'

Absolutely.

> Is shipping it enough or should we also convert/archive/install it through CMake?

Your call. AFAIC, the .org file is enough.

**Comment by AvtechScientific** [comment]
Done.
