### ISSUE TITLE
Could not configure ASL in CMake

### ISSUE THREAD

**Issue by Vishnu-C** [AvtechScientific/ASL#30]
Hi all,
I am on generating VS 12 project files from cmake gui, I have configured the paths of Boost and openCL but I could not set the VTK_DIR, it turns back to VTK_DIR-NOT FOUND every time i click configure, but surprisingly I use the same path for building VTK applications and I face no problem in that. Please help me out.

**Comment by AvtechScientific** [comment]
Try to ask on cmake support mailing list/IRC channel. You also may try to use command line.
