### ISSUE TITLE
OpenCL 1.0 support library

### ISSUE THREAD

**Issue by jinz2014** [AvtechScientific/ASL#33]
Could you provide a library just for OpenCL 1.0 support ?   Intel Altera OpenCL only supports OpenCL 1.0.

Thanks,
-z

So I have the following errors during the build
CMakeFiles/asl-hardware.dir/asl-hardware.cc.o: In function `cl::detail::ReferenceHandler<_cl_device_id*>::retain(_cl_device_id*)':
asl-hardware.cc:(.text._ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE6retainES3_[_ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE6retainES3_]+0x14): undefined reference to `clRetainDevice'
CMakeFiles/asl-hardware.dir/asl-hardware.cc.o: In function `cl::detail::ReferenceHandler<_cl_device_id*>::release(_cl_device_id*)':
asl-hardware.cc:(.text._ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE7releaseES3_[_ZN2cl6detail16ReferenceHandlerIP13_cl_device_idE7releaseES3_]+0x14): undefined reference to `clReleaseDevice'
../src/acl/libaslacl.so.0.1.7: undefined reference to `clCreateSubBuffer'
collect2: error: ld returned 1 exit status

**Comment by AvtechScientific** [comment]
OpenCL 1.0 is quite old. You should ask Altera to accelerate their R&D to support 1.1as well.
PS: this been said - the difference between v1.0 and v.1.1 is not that dramatic and you might try to downgrade ASL to OpenCL 1.0 on your own.
