### ISSUE TITLE
multiple GPUS

### ISSUE THREAD

**Issue by waynezw0618** [AvtechScientific/ASL#40]
Dear everyone
does anyone know, how can I setup case which can run on multiple GPUs, especially a cluster with distributed GPUs machines.

Thanks

**Comment by AvtechScientific** [comment]
Hello @waynezw0618,
all available devices (GPUs, CPUs, etc) are listed in [Hardware::queues](https://github.com/AvtechScientific/ASL/blob/master/src/acl/aclHardware.h#L153) so you can use some or all of them on a specific machine. If you run your computations on a cluster you can use e.g. MPI.

Best luck!
