### ISSUE TITLE
how to run simulation on multi GPUs across different nodes in a cluster

### ISSUE THREAD

**Issue by waynezw0618** [AvtechScientific/ASL#41]
Dear everyone
I want to use multi GPUS across different nodes in a cluster. how can I do that with ASL?

/Wei

**Comment by AvtechScientific** [comment]
all available devices (GPUs, CPUs, etc) are listed in [Hardware::queues](https://github.com/AvtechScientific/ASL/blob/master/src/acl/aclHardware.h#L153) so you can use some or all of them on a specific machine. If you run your computations on a cluster you can use e.g. MPI.
