### ISSUE TITLE
Source files without copyright information

### ISSUE THREAD

**Issue by ghisvail** [AvtechScientific/ASL#5]
licensecheck -r . | grep "No copyright"
./src/pics/grids/2Dconcatination.tex: _No copyright_ UNKNOWN

Please add a suitable copyright header to the source files listed above.

**Comment by AvtechScientific** [comment]
It's not really a source file - just a Latex file, i.e. a doc file. I don't think there is a need to put copyright header into docs (like README.md).
Anyway this file is covered by the last paragraph here:
https://github.com/AvtechScientific/ASL/blob/master/examples/input_data/Media_Files_LICENSE.md

What do you think?

**Comment by ghisvail** [comment]
Latex files _are_ source files, and the pdf generated from them is a binary. A copyright header may not be appropriate for that type of file, granted. Still, this issue remains.

> Anyway this file is covered by the last paragraph here:
> https://github.com/AvtechScientific/ASL/blob/master/examples/input_data/Media_Files_LICENSE.md

This is ambiguous though. This notice is titled "Media Files" but the .tex is, as you stated earlier, documentation. The wording could definitely be improved.

Alternatively, you may consider shipping an additional COPYRIGHT file at the root of the source tree, which clearly explicits what files is governed by which license project-wise. Then, you can get rid of license exception files like the one you linked above.
