### ISSUE TITLE
Lack of instructions aimed to run a file with cc-extension  when the source of acquisition of ASL is not the source repository

### ISSUE THREAD

**Issue by Ricky-Tigg** [AvtechScientific/ASL#51]
**OS:** Fedora. Components covering ASL 0.1.7 acquired from a **Fedora's repository**.

Installed components:
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version} %{arch} %{summary}' libasl*
libASL 0.1.7 x86_64 ASL hardware accelerated multiphysics simulation platform
libASL-bin 0.1.7 x86_64 Binaries for libASL
libASL-doc 0.1.7 x86_64 Documentation for libASL
libASL-examples 0.1.7 x86_64 Examples for libASL
```
Hello. Location paths of **binaries** and **files with cc-extension** supplied by `libASL-examples` are respectively _/usr/bin/_ and _/usr/share/doc/libASL-examples_. [Here](https://github.com/AvtechScientific/ASL) though, the obvious is noticeable: the instructions covering the methodology to run a file given as example cannot be applied to an installation whose source is not the present repository. Hence unknown are the instructions to run that _locomotive.cc_.

**Comment by AvtechScientific** [comment]
`.cc` is a C++ source code file, so can't be run. What can be run is probably located on your Linux distribution inside `/usr/bin`. Can you, please, list the content that was added to that directory by ASL? Also, please, provide the content of `/usr/share/doc/libASL-examples`.

**Comment by Ricky-Tigg** [comment]
_libASL-bin_ as well installs into /usr/bin/, though a unique binary –_asl-hardware_–, despite of the mention "_Binaries_" in its summary.

Since the names of binaries installed by _libASL-examples_ begin by _asl-_, is use that characteristic to achieve the query. Output truncated
```
$ cd /usr/bin/; ls | grep ^asl-
asl-acousticWaves (...) asl-locomotive (...) asl-testSMDiff3C
```
Files with cc-extension installed by _libASL-examples_ go into those directories
```
$ cd /usr/share/doc/libASL-examples; ls
elastic  flow  heatTransfer  input  jumpingObjects  levelSet  massTransferSM
```
Example
```
$ ls flow/ | grep locomotive.cc
locomotive.cc
```

**Comment by Ricky-Tigg** [comment]
_libASL-bin_ as well installs into /usr/bin/, though a unique binary –_asl-hardware_–, despite of the mention "_Binaries_" in its summary.

Since the names of binaries installed by _libASL-examples_ begin by _asl-_, i use that characteristic to achieve the query. Output truncated
```
$ cd /usr/bin/; ls | grep ^asl-
asl-acousticWaves (...) asl-locomotive (...) asl-testSMDiff3C
```
Files with cc-extension installed by _libASL-examples_ go into those directories
```
$ cd /usr/share/doc/libASL-examples; ls
elastic  flow  heatTransfer  input  jumpingObjects  levelSet  massTransferSM
```
Example
```
$ ls flow/ | grep locomotive.cc
locomotive.cc
```

**Comment by AvtechScientific** [comment]
asl-locomotive is the compiled binary of locomotive.cc, so run `/usr/bin/asl-locomotive`...
