### ISSUE TITLE
Consider using CTest to register and run the test suite

### ISSUE THREAD

**Issue by ghisvail** [AvtechScientific/ASL#8]
You might want to register all test executables with `add_test` so that a build with `-DBUILD_TESTING=ON` allows automatic running of the test suite.

More info:
http://www.cmake.org/cmake/help/v3.0/command/add_test.html

**Comment by AvtechScientific** [comment]
Yes, we planed to enable it in the next release.

**Comment by ghisvail** [comment]
This will be required for the Debian packaging.

**Comment by AvtechScientific** [comment]
Ok, We'll try to do this next week. Hopefully there will be no other showstoppers.

**Comment by AvtechScientific** [comment]
Done:
 Input/Output tests are labled "IO" and may require input files
 Performance tests are labled "Performance"
 Run them: ctest [-C Release|Debug] -L Performance
 Exclude them: ctest [-C Release|Debug] -LE Performance
